// import { Link } from 'react-router-dom'
import ContactForm from '../components/contactform'
import OtherWork from '../components/otherwork'
import Adam from '../images/dissolve.png';

function MainPage() {
    return (
        <div>
            <section>
                <div>
                    <img src={Adam}/>
                </div>
                <div>
                    <h1>Adam H</h1>
                    <p>Front End Developer</p>
                    <p>Static Content Generated by React App</p>                    
                </div>

            </section>
            <section className='work-section'>
                <h2>Work</h2>
                <OtherWork />           
            </section>
            <section>
                <div>
                    <h2>Me</h2>
                    <p>a bit of a blurb abour yours truly</p>
                </div>
                <div>

                </div>
            </section>
            <section>
                <div>
                    <h2>Contact</h2>
                    <ContactForm />
                </div>
            </section>
        </div>
    )

}

export default MainPage